import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './lp-style.css'; // 追加
import { Navigation } from '@/components/Globals/Navigation/Navigation';
import { PreviewNotice } from '@/components/Globals/PreviewNotice/PreviewNotice';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} gradient-mesh-background`}>
        <PreviewNotice />
        {children}
      </body>
    </html>
  );
}
