import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', zIndex: -1 }}>
          <div className="mesh-container" style={{ width: '100%', height: '100%' }}>
            <div className="gradient-blob gradient-blob-1"></div>
            <div className="gradient-blob gradient-blob-2"></div>
            <div className="gradient-blob gradient-blob-3"></div>
            <div className="gradient-blob gradient-blob-4"></div>
            <div className="gradient-blob gradient-blob-5"></div>
            <div className="noise-overlay"></div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}